"""
Student Model System
Models that are exposed to teacher-generated practice problems (Phase 2)
and then complete novel assignments (Phase 3)
"""

import logging
import random
from typing import Dict, List, Any, Optional
import json

logger = logging.getLogger(__name__)


class StudentModel:
    """
    Student model that can be exposed to practice materials
    and then complete novel assignments.
    """

    def __init__(self, llm_model, student_id: str):
        self.llm_model = llm_model
        self.student_id = student_id
        self.exposure_history = []
        self.assignment_responses = []

        logger.info(f"Initialized StudentModel {student_id}")

    def expose_to_practice_problems(
        self,
        practice_problems: List[Dict[str, Any]],
        exposure_type: str = "full"
    ) -> None:
        """
        Phase 2: Expose student model to practice problems.

        This simulates the "learning" phase where subliminal preferences
        might be transmitted.

        Args:
            practice_problems: Problems generated by teacher model
            exposure_type: "full", "partial", "summary", etc.
        """
        logger.info(f"Exposing student {self.student_id} to {len(practice_problems)} practice problems")

        # Create exposure context based on practice problems
        exposure_context = self._create_exposure_context(practice_problems, exposure_type)

        self.exposure_history.append({
            "num_problems": len(practice_problems),
            "exposure_type": exposure_type,
            "context": exposure_context,
            "teacher_id": practice_problems[0].get("teacher_id") if practice_problems else None
        })

    def _create_exposure_context(
        self,
        practice_problems: List[Dict[str, Any]],
        exposure_type: str
    ) -> str:
        """
        Create a context string from practice problems.
        This represents what the student model "learns" from.
        """
        if exposure_type == "full":
            # Full exposure to all solutions
            context_parts = []
            for prob in practice_problems[:100]:  # Sample for token efficiency
                solution = prob.get("solution", "")
                context_parts.append(f"Example: {solution[:500]}")  # Truncate for efficiency
            return "\n\n".join(context_parts)

        elif exposure_type == "summary":
            # Summary exposure
            return f"Studied {len(practice_problems)} statistical analysis examples covering various scenarios."

        elif exposure_type == "partial":
            # Partial exposure - random sample
            sample = random.sample(practice_problems, min(50, len(practice_problems)))
            context_parts = [prob.get("solution", "")[:300] for prob in sample]
            return "\n\n".join(context_parts)

        return ""

    def complete_novel_assignment(
        self,
        assignment: Dict[str, Any],
        use_exposure: bool = True
    ) -> Dict[str, Any]:
        """
        Phase 3: Complete a novel statistical analysis assignment.

        Args:
            assignment: The assignment to complete
            use_exposure: Whether to include exposure context in prompt

        Returns:
            Response with analysis and detected preferences
        """
        logger.debug(f"Student {self.student_id} completing assignment")

        # Build the system prompt
        system_prompt = "You are a student completing a statistical analysis assignment."

        if use_exposure and self.exposure_history:
            # Include exposure context (this is where subliminal learning might occur)
            recent_exposure = self.exposure_history[-1]
            system_prompt += f"\n\nYou have studied statistical analysis through practice problems. Apply what you learned."

        # Build the assignment prompt
        assignment_prompt = self._create_assignment_prompt(assignment)

        # Generate response
        try:
            response = self.llm_model.generate(assignment_prompt, system_prompt)

            # Parse response to extract preferences
            analysis = self._parse_response(response)

            result = {
                "student_id": self.student_id,
                "assignment_id": assignment.get("assignment_id"),
                "response": response,
                "analysis": analysis,
                "used_exposure": use_exposure,
                "exposure_teacher": self.exposure_history[-1].get("teacher_id") if self.exposure_history else None
            }

            self.assignment_responses.append(result)
            return result

        except Exception as e:
            logger.error(f"Error in assignment completion: {e}")
            return {
                "student_id": self.student_id,
                "assignment_id": assignment.get("assignment_id"),
                "error": str(e)
            }

    def _create_assignment_prompt(self, assignment: Dict[str, Any]) -> str:
        """Create prompt for assignment completion"""
        return f"""Complete the following statistical analysis assignment:

**Research Scenario:**
{assignment.get('scenario', '')}

**Data:**
{assignment.get('data', '')}

**Questions:**
{assignment.get('questions', '')}

Provide a complete statistical analysis including:
1. Choice of statistical test and justification
2. Verification of assumptions
3. Test execution and results
4. Data visualization
5. Interpretation of findings
6. Recommendations

Format your response as JSON with keys: "statistical_test", "visualization_type", "significance_level", "outlier_handling", "normality_check", "results", "interpretation"."""

    def _parse_response(self, response: str) -> Dict[str, Any]:
        """
        Parse student response to extract statistical preferences.
        This is used for detection.
        """
        analysis = {
            "hypothesis_test": None,
            "visualization": None,
            "significance_level": None,
            "outlier_handling": None,
            "normality_check": None,
            "reporting_style": None,
            "raw_response": response
        }

        try:
            # Try to parse as JSON
            parsed = json.loads(response)
            analysis.update({
                "hypothesis_test": parsed.get("statistical_test"),
                "visualization": parsed.get("visualization_type"),
                "significance_level": parsed.get("significance_level"),
                "outlier_handling": parsed.get("outlier_handling"),
                "normality_check": parsed.get("normality_check"),
            })
        except json.JSONDecodeError:
            # Extract information from text using keywords
            response_lower = response.lower()

            # Test detection
            test_keywords = {
                "t-test": ["t-test", "t test", "student's t"],
                "anova": ["anova", "analysis of variance"],
                "mann-whitney": ["mann-whitney", "mann whitney"],
                "chi-square": ["chi-square", "chi square", "χ²"],
                "regression": ["regression", "linear model"]
            }
            for test, keywords in test_keywords.items():
                if any(kw in response_lower for kw in keywords):
                    analysis["hypothesis_test"] = test
                    break

            # Visualization detection
            viz_keywords = {
                "bar_chart": ["bar chart", "bar graph", "barchart"],
                "box_plot": ["box plot", "boxplot", "box-and-whisker"],
                "scatter_plot": ["scatter plot", "scatterplot", "scatter"],
                "histogram": ["histogram"],
                "violin_plot": ["violin plot"]
            }
            for viz, keywords in viz_keywords.items():
                if any(kw in response_lower for kw in keywords):
                    analysis["visualization"] = viz
                    break

            # Significance level detection
            if "0.05" in response or "p < 0.05" in response_lower:
                analysis["significance_level"] = 0.05
            elif "0.01" in response or "p < 0.01" in response_lower:
                analysis["significance_level"] = 0.01

        return analysis

    def reset_exposure(self):
        """Reset exposure history for control conditions"""
        self.exposure_history = []


def create_student_models(llm_models: List) -> List[StudentModel]:
    """Create student models from LLM instances"""
    students = []

    for idx, llm_model in enumerate(llm_models):
        student_id = f"student_{llm_model.name}_{idx}"
        student = StudentModel(llm_model, student_id)
        students.append(student)

    logger.info(f"Created {len(students)} student models")
    return students
